apiVersion: apps/v1
kind: Deployment
metadata:
  name: terra-changer
spec:
  replicas: 2
  selector:
    matchLabels:
      app: terra-changer
  template:
    metadata:
      labels:
        app: terra-changer
    spec:
      containers:
        - name: terra-changer
          image: noirgt/changer:latest
          #command: ["/bin/chmod", "600", "/root/.ssh/id_rsa"]
          imagePullPolicy: "Always"
          envFrom:
            - configMapRef:
                name: terra-changer-env

          volumeMounts:
            - name: config
              mountPath: /changer/config.yml
              subPath: file-changer-config
            - name: ssh
              mountPath: /root/.ssh/id_rsa
              subPath: file-ssh-privkey
      volumes:
      - name: config
        configMap:
          name: terra-changer-conf
      - name: ssh
        configMap:
          name: terra-changer-conf
          defaultMode: 0600
