apiVersion: v1
kind: Service
metadata:
  name: zookeeper-cluster
spec:
  type: LoadBalancer
  selector:
    app: zookeeper-cluster
  ports:
  - name: client
    port: 2181
    targetPort: 2181 
  - name: follower
    port: 2888
    targetPort: 2888 
  - name: leader
    port: 3888
    targetPort: 3888   

---
apiVersion: v1
kind: Service
metadata:
  name: crs-zookeeper-0
  labels:
    app: zookeeper-cluster
spec:
  ports:
  - name: client
    port: 2181
    targetPort: 2181 
  - name: follower
    port: 2888
    targetPort: 2888 
  - name: leader
    port: 3888
    targetPort: 3888 
  selector:
    app: zookeeper-cluster
    component: zookeeper-cluster
    statefulset.kubernetes.io/pod-name: crs-zookeeper-0

---
apiVersion: v1
kind: Service
metadata:
  name: crs-zookeeper-1
  labels:
    app: zookeeper-cluster
spec:
  ports:
  - name: client
    port: 2181
    targetPort: 2181 
  - name: follower
    port: 2888
    targetPort: 2888 
  - name: leader
    port: 3888
    targetPort: 3888 
  selector:
    app: zookeeper-cluster
    component: zookeeper-cluster
    statefulset.kubernetes.io/pod-name: crs-zookeeper-1

---
apiVersion: v1
kind: Service
metadata:
  name: crs-zookeeper-2
  labels:
    app: zookeeper-cluster
spec:
  ports:
  - name: client
    port: 2181
    targetPort: 2181 
  - name: follower
    port: 2888
    targetPort: 2888 
  - name: leader
    port: 3888
    targetPort: 3888 
  selector:
    app: zookeeper-cluster
    component: zookeeper-cluster
    statefulset.kubernetes.io/pod-name: crs-zookeeper-2

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: crs-zookeeper
spec:
  replicas: 3
  serviceName: zookeeper-cluster
  selector:
    matchLabels:
      app: zookeeper-cluster
  template:
    metadata:
      labels:
        component: zookeeper-cluster
        app: zookeeper-cluster
    spec:
      containers:
      - name: zookeeper
        image: bitnami/zookeeper:latest
        securityContext:
          runAsUser: 0 
        ports:
        - containerPort: 2181
        - containerPort: 2888
        - containerPort: 3888
        lifecycle:
          postStart:
            exec:
              command:
                - "sh"
                - "-c"
                - >
                  echo $(( $(cat /etc/hosts | grep zookeeper | awk '{print($3)}' | awk '{split($0,array,"-")} END{print array[3]}') + 1 )) > /bitnami/zookeeper/data/myid
        env:
        - name: ALLOW_ANONYMOUS_LOGIN
          value: "yes"
        - name: ZOO_SERVERS
          value:  crs-zookeeper-0:2888:3888,crs-zookeeper-1:2888:3888,crs-zookeeper-2:2888:3888
